export const MAKE_SPLASH = 'MAKE_SPLASH';

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const GUEST_LOGIN_REQUEST = 'GUEST_LOGIN_REQUEST';
export const GUEST_LOGIN_SUCCESS = 'GUEST_LOGIN_SUCCESS';
export const GUEST_LOGIN_FAILURE = 'GUEST_LOGIN_FAILURE';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

export const VALIDATE_RESET_TOKEN_REQUEST = 'VALIDATE_RESET_TOKEN_REQUEST';
export const VALIDATE_RESET_TOKEN_SUCCESS = 'VALIDATE_RESET_TOKEN_SUCCESS';
export const VALIDATE_RESET_TOKEN_FAILURE = 'VALIDATE_RESET_TOKEN_FAILURE';

export const NEW_PASSWORD_REQUEST = 'NEW_PASSWORD_REQUEST';
export const NEW_PASSWORD_SUCCESS = 'NEW_PASSWORD_SUCCESS';
export const NEW_PASSWORD_FAILURE = 'NEW_PASSWORD_FAILURE';

export const MATRIX_LISTING_REQUEST = 'MATRIX_LISTING_REQUEST';
export const MATRIX_LISTING_SUCCESS = 'MATRIX_LISTING_SUCCESS';
export const MATRIX_LISTING_FAILURE = 'MATRIX_LISTING_FAILURE';

export const MATRIX_PERFORMER_REQUEST = 'MATRIX_PERFORMER_REQUEST';
export const MATRIX_PERFORMER_SUCCESS = 'MATRIX_PERFORMER_SUCCESS';
export const MATRIX_PERFORMER_FAILURE = 'MATRIX_PERFORMER_FAILURE';

export const MATRIX_PERFORMER_DATA_UPDATE_REQUEST =
  'MATRIX_PERFORMER_DATA_UPDATE_REQUEST';
export const MATRIX_PERFORMER_DATA_UPDATE_SUCCESS =
  'MATRIX_PERFORMER_DATA_UPDATE_SUCCESS';
export const MATRIX_PERFORMER_DATA_UPDATE_FAILURE =
  'MATRIX_PERFORMER_DATA_UPDATE_FAILURE';

export const MATRIX_PERFORMER_UPDATE = 'MATRIX_PERFORMER_UPDATE';
export const MATRIX_PERFORMER_RATE_UPDATE = 'MATRIX_PERFORMER_RATE_UPDATE';

export const MATRIX_UPDATE_TIME_REQUEST = 'MATRIX_UPDATE_TIME_REQUEST';
export const MATRIX_UPDATE_TIME_SUCCESS = 'MATRIX_UPDATE_TIME_SUCCESS';
export const MATRIX_UPDATE_TIME_FAILURE = 'MATRIX_UPDATE_TIME_FAILURE';

export const MATRIX_PERFORMER_SIGNIN_UPDATE_REQUEST =
  'MATRIX_PERFORMER_SIGNIN_UPDATE_REQUEST';
export const MATRIX_PERFORMER_SIGNIN_UPDATE_SUCCESS =
  'MATRIX_PERFORMER_SIGNIN_UPDATE_SUCCESS';
export const MATRIX_PERFORMER_SIGNIN_UPDATE_FAILURE =
  'MATRIX_PERFORMER_SIGNIN_UPDATE_FAILURE';

export const MATRIX_PERFORMER_RATE_REQUEST = 'MATRIX_PERFORMER_RATE_REQUEST';
export const MATRIX_PERFORMER_RATE_SUCCESS = 'MATRIX_PERFORMER_RATE_SUCCESS';
export const MATRIX_PERFORMER_RATE_FAILURE = 'MATRIX_PERFORMER_RATE_FAILURE';

export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';

export const UPDATE_PROFILE_DATA = 'UPDATE_PROFILE_DATA';

export const PRODUCT_LISTING_BY_STORE_ID_REQUEST =
  'PRODUCT_LISTING_BY_STORE_ID_REQUEST';
export const PRODUCT_LISTING_BY_STORE_ID_SUCCESS =
  'PRODUCT_LISTING_BY_STORE_ID_SUCCESS';
export const PRODUCT_LISTING_BY_STORE_ID_FAILURE =
  "PRODUCT_LISTING_BY_STORE_ID_FAILURE";
//PROFILE

//Get Profile 
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER_PROFILE_SUCCESS='GET_USER_PROFILE_SUCCESS'
export const GET_USER_PROFILE_FAILURE='GET_USER_PROFILE_FAILURE'
export const PROFILE_UPDATE_REQUEST = "PROFILE_UPDATE_REQUEST";
export const PROFILE_UPDATE_SUCCESS = "PROFILE_UPDATE_SUCCESS";
export const PROFILE_UPDATE_FAILURE = "PROFILE_UPDATE_FAILURE";
export const GET_PROFILE_PDF = "GET_PROFILE_PDF";
export const GET_PROFILE_PDF_SUCCESS = "GET_PROFILE_PDF_SUCCESS";
export const GET_PROFILE_PDF_FAILURE = "GET_PROFILE_PDF_FAILURE";


//Performer Profile
export const PERFORMER_PROFILE_REQUEST = "PERFORMER_PROFILE_REQUEST";

export const PERFORMER_PROFILE_SUCCESS = "PERFORMER_PROFILE_SUCCESS";

export const PERFORMER_PROFILE_FAILURE = "PERFORMER_PROFILE_FAILURE";

export const PDF_PERFORMER_PROFILE_REQUEST = "PDF_PERFORMER_PROFILE_REQUEST";
export const PDF_PERFORMER_PROFILE_SUCCESS = "PDF_PERFORMER_PROFILE_SUCCESS";
export const PDF_PERFORMER_PROFILE_FAILURE = "PDF_PERFORMER_PROFILE_FAILURE";

export const SAVE_PERFORMER_PROFILE_REQUEST = "SAVE_PERFORMER_PROFILE_REQUEST";
export const SAVE_PERFORMER_PROFILE_SUCCESS = "SAVE_PERFORMER_PROFILE_SUCCESS";
export const SAVE_PERFORMER_PROFILE_FAILURE = "SAVE_PERFORMER_PROFILE_FAILURE";

export const REMOVE_PERFORMER_PROFILE_REQUEST = "REMOVE_PERFORMER_PROFILE_REQUEST";
export const REMOVE_PERFORMER_PROFILE_SUCCESS = "REMOVE_PERFORMER_PROFILE_SUCCESS";
export const REMOVE_PERFORMER_PROFILE_FAILURE = "REMOVE_PERFORMER_PROFILE_FAILURE";

export const REPORT_PERFORMER_PROFILE_REQUEST = "REPORT_PERFORMER_PROFILE_REQUEST";
export const REPORT_PERFORMER_PROFILE_SUCCESS = "REPORT_PERFORMER_PROFILE_SUCCESS";
export const REPORT_PERFORMER_PROFILE_FAILURE = "REPORT_PERFORMER_PROFILE_FAILURE";

 
//

//custom Drawer 

//IN PROGREE
export const CUSTOM_DRAWER_INPROGREE = "CUSTOM_DRAWER_INPROGREE";
export const CUSTOM_DRAWER_INPROGREE_SUCCESS = "CUSTOM_DRAWER_INPROGREE_SUCCESS";
export const CUSTOM_DRAWER_INPROGREE_FAILURE = "CUSTOM_DRAWER_INPROGREE_FAILURE";
//
export const PROFILE_DELETE_REQUEST = "PROFILE_DELETE_REQUEST";
export const PROFILE_DELETE_SUCCESS = "PROFILE_DELETE_SUCCESS";
export const PROFILE_DELETE_FAILURE = "PROFILE_DELETE_FAILURE";

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_TO_CART = 'REMOVE_PRODUCT_TO_CART';
export const UPDATE_PRODUCT_QTY = 'UPDATE_PRODUCT_QTY';

export const UPDATE_DATA_FROM_LOCAL_STORAGE = 'UPDATE_DATA_FROM_LOCAL_STORAGE';

export const PLACE_ORDER_REQUEST = 'PLACE_ORDER_REQUEST';
export const PLACE_ORDER_SUCCESS = 'PLACE_ORDER_SUCCESS';
export const PLACE_ORDER_FAILURE = 'PLACE_ORDER_FAILURE';

export const ADD_FAVOURITE_REQUEST = 'ADD_FAVOURITE_REQUEST';
export const ADD_FAVOURITE_SUCCESS = 'ADD_FAVOURITE_SUCCESS';
export const ADD_FAVOURITE_FAILURE = 'ADD_FAVOURITE_FAILURE';

export const REMOVE_FROM_FAVOURITE_REQUEST = 'REMOVE_FROM_FAVOURITE_REQUEST';
export const REMOVE_FROM_FAVOURITE_SUCCESS = 'REMOVE_FROM_FAVOURITE_SUCCESS';
export const REMOVE_FROM_FAVOURITE_FAILURE = 'REMOVE_FROM_FAVOURITE_FAILURE';

export const GET_FAVOURITE_REQUEST = 'GET_FAVOURITE_REQUEST';
export const GET_FAVOURITE_SUCCESS = 'GET_FAVOURITE_SUCCESS';
export const GET_FAVOURITE_FAILURE = 'GET_FAVOURITE_FAILURE';

export const GET_USER_CARD_DATA_REQUEST = 'GET_USER_CARD_DATA_REQUEST';
export const GET_USER_CARD_DATA_SUCCESS = 'GET_USER_CARD_DATA_SUCCESS';
export const GET_USER_CARD_DATA_FAILURE = 'GET_USER_CARD_DATA_FAILURE';

export const SAVE_PAYMENT_METHOD_REQUEST = 'SAVE_PAYMENT_METHOD_REQUEST';
export const SAVE_PAYMENT_METHOD_SUCCESS = 'SAVE_PAYMENT_METHOD_SUCCESS';
export const SAVE_PAYMENT_METHOD_FAILURE = 'SAVE_PAYMENT_METHOD_FAILURE';

export const UPDATE_ORDER_TYPE = 'UPDATE_ORDER_TYPE';
export const CLEAR_CART = 'CLEAR_CART';
export const CLEAR_USER_DATA = 'CLEAR_USER_DATA';

export const GET_ALL_ORDERS_REQUEST = 'GET_ALL_ORDERS_REQUEST';
export const GET_ALL_ORDERS_SUCCESS = 'GET_ALL_ORDERS_SUCCESS';
export const GET_ALL_ORDERS_FAILURE = 'GET_ALL_ORDERS_FAILURE';

export const GET_USER_ADDRESSES_REQUEST = 'GET_USER_ADDRESSES_REQUEST';
export const GET_USER_ADDRESSES_SUCCESS = 'GET_USER_ADDRESSES_SUCCESS';
export const GET_USER_ADDRESSES_FAILURE = 'GET_USER_ADDRESSES_FAILURE';

export const UPLOAD_PROFILE_PIC_REQUEST = 'UPLOAD_PROFILE_PIC_REQUEST';
export const UPLOAD_PROFILE_PIC_SUCCESS = 'UPLOAD_PROFILE_PIC_SUCCESS';
export const UPLOAD_PROFILE_PIC_FAILURE = 'UPLOAD_PROFILE_PIC_FAILURE';

export const CLEAR_FAVOURITES_DATA = 'CLEAR_FAVOURITES_DATA';

export const GET_APP_SETTINGS_REQUEST = 'GET_APP_SETTINGS_REQUEST';
export const GET_APP_SETTINGS_SUCCESS = 'GET_APP_SETTINGS_SUCCESS';
export const GET_APP_SETTINGS_FAILURE = 'GET_APP_SETTINGS_FAILURE';
